apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        livenessProbe: #LifelinessProbe
          httpGet: #Make a request to the path "/" in the port 80
            path: /
            port: 80
          initialDelaySeconds: 10 #Once the pod is started, wait for 10" to make the first request
          timeoutSeconds: 10 #Request is done each 10"
