apiVersion: apps/v1 #Indicate the version of Kubernetes
kind: Deployment #Type of resource 
metadata:
  name: deployment #Name of the recourse
  labels:
    app: nginx
spec:
  replicas: 3 #Specify a ReplicaSet in the deployment
  selector: #Filter the pods by label. Independently the container in which they are
    matchLabels:
      app: nginx
  template: #Specify the pods in the deployment
    metadata:
      labels:
        app: nginx #Label of the pod
    spec: #Specify the recourses into the pod
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      - name: content
        image: alpine
        volumeMounts:
        - name: shared-data
          mountPath: /pod-data
        command: ["/bin/sh"]
        args: ["-c", "echo Hola Openwebinars! > /pod-data/index.html && tail -f /dev/null"]
