kind: Service #Type of resource 
apiVersion: v1 #Indicate the version of Kubernetes
metadata:
  name: service
spec:
  type: NodePort #Indicate type of service
  selector:
    app: nginx #Apply the services just to the pods with this label
  ports:
  - port: 80 #Source port
    nodePort: 30080 #Target port
