apiVersion: apps/v1 #Indicate the version of Kubernetes
kind: Deployment #Type of resource 
metadata:
  name: deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: pchico83/nginx #Private image pushed in the register
        ports:
        - containerPort: 80
      imagePullSecrets: #Indicate the credentials to do the pull from docker registry
      - name: regpablo #Name of the secret. Secret will be created directly in Kubernetes via CLI
