apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: NodePort #Expose the container vote by NodePort
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote
