apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers: #This container doesn't expose any API --> It hasn't got any service
      - image: dockersamples/examplevotingapp_worker
        name: worker
